CREATE TABLE IF NOT EXISTS Musician (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL, 
	Year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Soundtrack (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Duration INTEGER NOT NULL,
	AlbumId INTEGER NOT NULL REFERENCES Album(Id)
);

CREATE TABLE IF NOT EXISTS Genre (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Songbook (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	Release_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SongbookSoundtrack (
	SoundtrackId INTEGER REFERENCES Soundtrack(Id),
	SongbookId INTEGER REFERENCES Songbook(Id),
	CONSTRAINT SoundtrackSongbook_pk PRIMARY KEY (SoundtrackId, SongbookId)	
);

CREATE TABLE IF NOT EXISTS MusicianGenre (
	MusicianId INTEGER REFERENCES Musician(Id),
	GenreId INTEGER REFERENCES Genre(Id),
	CONSTRAINT MusicianGenre_pk PRIMARY KEY (MusicianId, GenreId)
);

CREATE TABLE IF NOT EXISTS MusicianAlbum (
	MusicianId INTEGER REFERENCES Musician(Id),
	AlbumId INTEGER REFERENCES Album(Id),
	CONSTRAINT MusicianAlbum_pk PRIMARY KEY (MusicianId, AlbumId)
);